Update examples.yml
Signed-off-by: Michael Yuan <michael@secondstate.io>

diff --git a/.github/workflows/examples.yml b/.github/workflows/examples.yml
--- a/.github/workflows/examples.yml
+++ b/.github/workflows/examples.yml
@@ -40,20 +40,6 @@ jobs:
         sudo mv libtensorflowlite_c.so /usr/local/lib
         sudo mv libtensorflowlite_flex.so /usr/local/lib
         curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | sudo bash -s -- -v $VERSION --plugins wasi_nn-tensorflowlite -p /usr/local
-    
-    - name: Client example
-      run: |
-        cd client
-        cargo build --target wasm32-wasi --release
-        wasmedgec target/wasm32-wasi/release/wasmedge_hyper_client.wasm wasmedge_hyper_client.wasm
-        resp=$(wasmedge wasmedge_hyper_client.wasm)
-        echo "$resp"
-        if [[ $resp == *"WasmEdge"* ]]; then
-          echo -e "Execution Success!"
-        else
-          echo -e "Execution Fail!"
-          exit 1
-        fi
         
     - name: Server example
       run: |
@@ -111,5 +97,18 @@ jobs:
           echo -e "Execution Fail!"
           exit 1
         fi
-        
+
+    - name: Client example
+      run: |
+        cd client
+        cargo build --target wasm32-wasi --release
+        wasmedgec target/wasm32-wasi/release/wasmedge_hyper_client.wasm wasmedge_hyper_client.wasm
+        resp=$(wasmedge wasmedge_hyper_client.wasm)
+        echo "$resp"
+        if [[ $resp == *"WasmEdge"* ]]; then
+          echo -e "Execution Success!"
+        else
+          echo -e "Execution Fail!"
+          exit 1
+        fi
     
